### ISSUE TITLE
make it to where some people can put keys on decompressing .zs files

### ISSUE THREAD

**Issue by Murray2k6** [TotkMods/Totk.ZStdTool#11]
title a recommendation to put .zs dev key to whomever made so mod, that way no-one can steal their hard work without consent. yes its possible to decompress the same files over and over, which needs fixed with whoever made the mod can put a custom encryption on the work they made.

**Comment by ArchLeaders** [comment]
You'd need the key to use the mod, so you may as well just restrict the entire mod as you would the zs dictionary.

**Comment by Murray2k6** [comment]
> You'd need the key to use the mod, so you may as well just restrict the entire mod as you would the zs dictionary.

im talking about the dev of the mod making a key so the mod would stay encrypted if they released it and noone had permission to copy what they did, not talking about totk files itself, just the work people edited inside of it

**Comment by HGStone** [comment]
how would the game use it if it was encrypted

**Comment by ArchLeaders** [comment]
> how would the game use it if it was encrypted

Precisely what I was thinking xD

**Comment by ArchLeaders** [comment]
> > You'd need the key to use the mod, so you may as well just restrict the entire mod as you would the zs dictionary.
> 
> im talking about the dev of the mod making a key so the mod would stay encrypted if they released it and noone had permission to copy what they did, not talking about totk files itself, just the work people edited inside of it

What part of the mod isn't the TotK files?

**Comment by Murray2k6** [comment]
> how would the game use it if it was encrypted

not really encrypted i meant as in just something like so but also so the game will still use it. Just thinking about a persons work so no'one can steal and paste their name on the work the dev of the mod did so hard on. no'one wants their stuff to be stolen in any matter right?

**Comment by ArchLeaders** [comment]
> > how would the game use it if it was encrypted
> 
> not really encrypted i meant as in just something like so but also so the game will still use it. Just thinking about a persons work so no'one can steal and paste their name on the work the dev of the mod did so hard on. no'one wants their stuff to be stolen in any matter right?

What would you encrypt/objuscate, if not the mod files? And how to you propose to lock something from users, that the game can also read?

**Comment by Murray2k6** [comment]
> > > how would the game use it if it was encrypted
> > 
> > 
> > not really encrypted i meant as in just something like so but also so the game will still use it. Just thinking about a persons work so no'one can steal and paste their name on the work the dev of the mod did so hard on. no'one wants their stuff to be stolen in any matter right?
> 
> What would you encrypt/objuscate, if not the mod files? And how to you propose to lock something from users, that the game can also read?

if you think its locking it from users, im saying that the tools need something like key insertion because some people have patreon, i do not think those people want the work stolen and plus the game would read it anyway it almost sounds like you don't want this because you probably look inside these files that some people have already edited. that is not knowledge that is stolen work in a persons hand. twisting my words will not subjugate what actually needs to be done. for example if this was skyrim a different game yea but also people tell them to get permission from them first before they can edit and reupload those edits. some people run off with the mods in hand that devs made, reupload it in there name and call it theirs with no permissions or credit given, just so they can still what is made to conclude mods not being made anymore by the dev in question. i said encrypt at first but i also mean something not dealing with encryption which was an example term used. i don't know where you get that im still talking about encryption. i should have been more concrete on what i meant. can keep twisting words but it gets nowhere but into a debate. just find another algorithm for the decompression tools but not the encryption part that keeps being talked about. keep devs of mods the same dev, do not let someone take off with it. heck would you like it if someone stole anything of yours and put their name on top of yours and erasing your name?

**Comment by ArchLeaders** [comment]
> > > > how would the game use it if it was encrypted
> > > 
> > > 
> > > not really encrypted i meant as in just something like so but also so the game will still use it. Just thinking about a persons work so no'one can steal and paste their name on the work the dev of the mod did so hard on. no'one wants their stuff to be stolen in any matter right?
> > 
> > 
> > What would you encrypt/objuscate, if not the mod files? And how to you propose to lock something from users, that the game can also read?
> 
> if you think its locking it from users, im saying that the tools need something like key insertion because some people have patreon, i do not think those people want the work stolen and plus the game would read it anyway it almost sounds like you don't want this because you probably look inside these files that some people have already edited. that is not knowledge that is stolen work in a persons hand. twisting my words will not subjugate what actually needs to be done. for example if this was skyrim a different game yea but also people tell them to get permission from them first before they can edit and reupload those edits. some people run off with the mods in hand that devs made, reupload it in there name and call it theirs with no permissions or credit given, just so they can still what is made to conclude mods not being made anymore by the dev in question. i said encrypt at first but i also mean something not dealing with encryption which was an example term used. i don't know where you get that im still talking about encryption. i should have been more concrete on what i meant. can keep twisting words but it gets nowhere but into a debate. just find another algorithm for the decompression tools but not the encryption part that keeps being talked about. keep devs of mods the same dev, do not let someone take off with it. heck would you like it if someone stole anything of yours and put their name on top of yours and erasing your name?

I'm not questioning your logic here, I don't want mods to be stolen just as much as you do. I'm merely trying to convey that there is nothing we can do (afaik) to restrict access to a mod that does not also ***restrict the game from using it.***

**To summerize:**
If a developer makes a mod that edits a `.pack` file, and the author has made it so that only he can open it. How does the game engine open it? It's not the mod author, it doesn't know how to open the file.

If you have do have a concept in mind for how this could be done. That is, that only the mod developer and the game engine can open it. I'm open to discussing it.

**Comment by Murray2k6** [comment]
maybe a signature of the author of mod for the zs file maybe if it can be done after compressing it and maybe the game will still read it like say compress and save (mod title, mod author, version number).

**Comment by ArchLeaders** [comment]
> maybe a signature of the author of mod for the zs file maybe if it can be done after compressing it and maybe the game will still read it like say compress and save (mod title, mod author, version number).

How would that stop the users from opening it?

**Comment by Murray2k6** [comment]
> > maybe a signature of the author of mod for the zs file maybe if it can be done after compressing it and maybe the game will still read it like say compress and save (mod title, mod author, version number).
> 
> How would that stop the users from opening it?

since there's no way probably to do so but im thinking of maybe like a patch merge addition besides the compression and decompressor tool, super nintendo had something called ips patcher for hacks that people have made, is it possible to do the same? and make another tool to read so patch file like a mod requirement, for example skse for game skyrim which is another game and a mod loader of sorts but also they read plugins so forth making it read so .zs file that was edited or to call common code that a modder has put in the zs file to be called upon that no'one would know but the author and then the game would still use this code that will verify these files that the modder has edited by checking the file sizes. yes it still wouldn't be encrypted but also the other person cannot overwrite that the modder has done if the verification is wrong. so i guess encryption wouldn't be ideal at the moment until a person like a dev can put a hidden key inside the zs file like a hash of sorts that the game wouldn't read but only the ztool when it ask for the hash number

**Comment by ArchLeaders** [comment]
> > > maybe a signature of the author of mod for the zs file maybe if it can be done after compressing it and maybe the game will still read it like say compress and save (mod title, mod author, version number).
> > 
> > 
> > How would that stop the users from opening it?
> 
> since there's no way probably to do so but im thinking of maybe like a patch merge addition besides the compression and decompressor tool, super nintendo had something called ips patcher for hacks that people have made, is it possible to do the same? and make another tool to read so patch file like a mod requirement, for example skse for game skyrim which is another game and a mod loader of sorts but also they read plugins so forth making it read so .zs file that was edited or to call common code that a modder has put in the zs file to be called upon that no'one would know but the author and then the game would still use this code that will verify these files that the modder has edited by checking the file sizes. yes it still wouldn't be encrypted but also the other person cannot overwrite that the modder has done if the verification is wrong. so i guess encryption wouldn't be ideal at the moment until a person like a dev can put a hidden key inside the zs file like a hash of sorts that the game wouldn't read but only the ztool when it ask for the hash number

Unfortunately something like this isn't really possible with zStandard, and assembly patches are far beyond the scope of this tool. Furthermore, if the game can read it, so can modders, who are very good at hacking into things like the game would.

If any other ideas feel free to post them here, but for now I'm going to close the issue.
