### ISSUE TITLE
"Invalid game path"

### ISSUE THREAD

**Issue by ItzSimplyCinnamon** [TotkMods/Totk.ZStdTool#13]
![image](https://github.com/TotkMods/Totk.ZStdTool/assets/141779734/379cb20f-66c3-4fd1-b5f1-5ac1f4f2044a)
I'm trying to use this to follow a tutorial for modding that I saw on gamebanana. However, despite me setting the game path to exactly where my romfs folder is, when I try to decompress the file, it pops up with an error saying "Invalid game path". I tried moving my romfs folder, I tried renaming my romfs folder, I tried older versions of the tool and nothing worked. I saw another post that was closed that didn't have anything written in it, so I decided to make this post. On gamebanana someone said that this doesn't work with 1.1.2, but I don't know.

**Comment by ItzSimplyCinnamon** [comment]
By the way, the spot where it says MYUSER was actually my user when I tried using the tool, I put that there to not leak my real name.

**Comment by ArchLeaders** [comment]
Means the required game files are not found in the provided folder. Make sure `Pack/ZsDic.pack.zs` exists in your game files.
