### ISSUE TITLE
Program won't open (.NET 7 Runtime IS installed)

### ISSUE THREAD

**Issue by fawfulthegreat** [TotkMods/Totk.ZStdTool#14]
I installed .net 7 runtime from here: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-7.0.12-windows-x86-installer

I also restarted my PC just in case. Even after all that, this exe file only opens a split second of the CMD window and closes. To my knowledge I followed everything I needed to in setup. One thing I did notice is that the runtime seemed to install instantly with no waiting, but it said it was successful.

**Comment by ArchLeaders** [comment]
You need the x64 runtime, not the x86 (32-bit) one which you installed.

https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-7.0.12-windows-x64-installer
