### ISSUE TITLE
ZSDic file path is improperly selected in GUI mode

### ISSUE THREAD

**Issue by Catalyzzt** [TotkMods/Totk.ZStdTool#8]
The path to `romfs/Pack/ZsDic.pack.zs` is selected based on the directory of the executable, even when in GUI mode. It would seem desirable to allow the user to run the executable from anywhere (e.g. downloads folder) and find the dictionary file dynamically based on the folder selected for decompression by searching for `Pack/ZsDic.pack.zs`. Also, a "ZSDic file is missing!" error would be useful.

**Comment by ArchLeaders** [comment]
The path in the settings should be the absolute path to your game files, not a relative path from the executable location. Might be able to change the error message though.
